### PR TITLE
Fix GitHub Rate limit error

### PR DESCRIPTION
**Pull request by aaclan-ebi**
I think there are problems with the original design of this component and how metadata schemas are published. I'll probably try to document other problems I see in a different document. But in the context of the rate limit exceeded/github api key issue, the problem is the usage of Github personal access token to communicate with GitHub API which I retained because OAuth (User authentication) can't be done inside the lambda function. 

Using personal access tokens has a request rate limit of 5000 request / hour. This component is doing requests to
- Get repo info
- Get contents of each directory
- Get content of each json file 

This usage pattern might hit the limit as the repo grows in the future.

### CODE REVIEW

**Comment by aaclan-ebi** [comment]
Upon doing further reading, use of personal access token is acceptable and recommended. When generating access token, the scope/permissions of the token should be limited. 
https://developer.github.com/v3/auth/#via-oauth-and-personal-access-tokens
https://python.gotrained.com/search-github-api/

If ever the 5000 request rate limit has been reached, we could explore downloading the specific folder via svn as noted in the link. Or processing only the files which has changed.

```
from svn.remote import RemoteClient
....

def download_folder(url):
    if 'tree/master' in url:
        url = url.replace('tree/master', 'trunk')

    r = RemoteClient(url)
    r.export('output')
```

**Comment by aaclan-ebi** [comment]
Code coverage drastically went down since I removed the test which do actual calls to GitHub API. This codebase needs some refactoring and more comprehensive tests. Not gonna include that in this change to fix the issue sooner.

**Comment by MightyAx** [comment]
> Code coverage drastically went down since I removed the test which do actual calls to GitHub API. This codebase needs some refactoring and more comprehensive tests. Not gonna include that in this change to fix the issue sooner.

Can you open a ticket so that we don't forget to do this work?

**Review by MightyAx — APPROVED** [review]

**Comment by aaclan-ebi** [comment]
https://docs.aws.amazon.com/code-samples/latest/catalog/python-secretsmanager-secrets_manager.py.html

**Review by ESapenaVentura — APPROVED** [review]
LGTM

**Pull request merged**
