### PR TITLE
Snyk wizard fixes

### LINKED ISSUE #1104: Remediate Critical lodash vulnerability
GitHub reports the following **Critical** severity vulnerability in HumanCellAtlas/metadata-schema and HumanCellAtlas/metadata-schema-publisher. Please remediate by the end of Q3 Milestone 3.

### Description
lodash

### Suggested Remediation
Upgrade lodash to version 4.17.13 or later

### Details
Affected versions of lodash are vulnerable to Prototype Pollution. The function defaultsDeep could be tricked into adding or modifying properties of Object.prototype using a constructor payload.

### PR DESCRIPTION
**Pull request by aaclan-ebi**
Fixes HumanCellAtlas/metadata-schema#1104

### CODE REVIEW

**Comment by ESapenaVentura** [comment]
it seems that the travis builds are failing due to an API rate limit?

```
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for 35.192.85.2. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", "documentation_url": "https://developer.github.com/v3/#rate-limiting"}
```

I have no idea what is happening as I have never looked into the scripts for this repo

**Comment by aaclan-ebi** [comment]
Yes, we just found out this now. Please see ticket https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/611

**Comment by ESapenaVentura** [comment]
Oh, ok! Then aside from that, this LGTM! 👍

**Review by ESapenaVentura — APPROVED** [review]

**Review by adrazhi — COMMENTED** [review]
👍

**Pull request merged**
